name: Tests
on: [push, pull_request]
jobs:
  amd64:
    uses: ./.github/workflows/tests-template.yaml
    with:
      arch: amd64
      runs-on: ubuntu-latest
      targets: "['linux-test-smoke',
        'linux-integration-1-cpu',
        'linux-integration-2-cpu',
        'linux-integration-4-cpu',
        'linux-unit-4-cpu-race',
        'linux-386-unit-1-cpu',
        'all-build']"
